name = "CrystallographicFFT"
uuid = "77d87cf4-6451-5050-a4a3-5ce7c515c7a6"
version = "0.1.0"
authors = ["Yixin Liu <lyx@fudan.edu.cn>"]

[workspace]
projects = ["test", "docs"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AbstractFFTs = "1.5.0"
Crystalline = "0.6.23"
FFTW = "1.10.0"
KernelAbstractions = "0.9.39"
LinearAlgebra = "1.12.0"
SparseArrays = "1.12.0"
StaticArrays = "1.9.16"
julia = "1.11"
