name = "CrystallographicFFT"
uuid = "77d87cf4-6451-5050-a4a3-5ce7c515c7a6"
version = "0.1.0"
authors = ["Yixin Liu <lyx@fudan.edu.cn>"]

[workspace]
projects = ["test", "docs"]

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Crystalline = "0.6.23"
LinearAlgebra = "1.12.0"
julia = "1.11"
