name = "CrystallographicFFT"
uuid = "77d87cf4-6451-5050-a4a3-5ce7c515c7a6"
version = "0.1.0"
authors = ["Yixin Liu <lyx@fudan.edu.cn>"]

[workspace]
projects = ["test", "docs"]

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Crystalline = "0.6.23"
FFTW = "1.10.0"
LinearAlgebra = "1.12.0"
SparseArrays = "1.12.0"
julia = "1.11"
