[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
CrystallographicFFT = "77d87cf4-6451-5050-a4a3-5ce7c515c7a6"

[compat]
Documenter = "1"

[sources]
CrystallographicFFT = {path = ".."}
